from django.conf import settings

MONGO_ATLAS_VECTOR_INDEX_NAME = settings.MONGO_ATLAS_VECTOR_INDEX_NAME
MONGO_DB_COLLECTION = settings.MONGO_DB_COLLECTION
MONGO_DB_NAME = settings.MONGO_DB_NAME
MONGO_URI = settings.MONGO_URI
OPEN_AI_API_KEY = settings.OPENAI_API_KEY
OPEN_AI_MODEL = settings.OPEN_AI_MODEL

